rewrote cal from scratch, using new /usr/bin/cal features

diff --git a/bin/cal b/bin/cal
--- a/bin/cal
+++ b/bin/cal
@@ -1,113 +1,125 @@
+#!/bin/bash
 
-function convmon ()
+#
+# cal - the standard cal plus a few additions:
+#   * handle month names, including "now"
+#   * handle ranges of months
+#   * interpret an arg <= 12 as month instead of a year
+#     back in Roman times
+#
+
+function conv_to_num ()
 {
-    mon=`echo $1 | sed 's/\(...\).*/\1/' | tr '[:upper:]' '[:lower:]'`;
-    case "$mon" in
-        "now") return `date +'%m' | sed 's/^0//'` ;;
-        "jan") return 1 ;;
-        "feb") return 2 ;;
-        "mar") return 3 ;;
-        "apr") return 4 ;;
-        "may") return 5 ;;
-        "jun") return 6 ;;
-        "jul") return 7 ;;
-        "aug") return 8 ;;
-        "sep") return 9 ;;
-        "oct") return 10 ;;
-        "nov") return 11 ;;
-        "dec") return 12 ;;
-        *) return -1 ;;
-    esac
+    local arg=$1
+    if [[ $arg =~ ^[[:digit:]]+$ ]]; then
+       echo $arg
+    else
+       arg=`echo $arg | sed 's/\(...\).*/\1/' | tr '[:upper:]' '[:lower:]'`
+       case "$arg" in
+           "now") echo `date +'%m' | sed 's/^0//'` ;;
+           "jan") echo 1 ;;
+           "feb") echo 2 ;;
+           "mar") echo 3 ;;
+           "apr") echo 4 ;;
+           "may") echo 5 ;;
+           "jun") echo 6 ;;
+           "jul") echo 7 ;;
+           "aug") echo 8 ;;
+           "sep") echo 9 ;;
+           "oct") echo 10 ;;
+           "nov") echo 11 ;;
+           "dec") echo 12 ;;
+           *) echo "\"$arg\" doesn't make sense as a month or a year" >&2 && exit 1 ;;
+       esac
+    fi
 }
 
 # simplest case- no args
 if [ $# -eq 0 ]; then
-    /usr/bin/cal
-    return
-elif [ $# -eq 2 ]; then
-    # two args are month (or month range) and year
-    # easy to know what is what
-    month=$1
-    year=$2
-elif [ $# -eq 1 ]; then
-    # single arg is one of:
-    #    a month range (presence of -)
-    #    a month (string or number <= 12)
-    #    a year (any other number)
-    arg=$1
-    # if it is all numbers, then pick between month (<=12) or year
-    if [[ "$arg" =~ "^[0-9]+$" ]]; then
-        if [ "$arg" -gt "12" ]; then
-            # easy case, just a year
-            /usr/bin/cal $arg
-            return
-        else
-            month=$arg
-            year=`date +'%Y'`
-        fi
-    else
-        # anything besides numbers is a month
-        month=$arg
-        year=`date +'%Y'`
-    fi
-else
-    echo "Usage: $0 [ month ] [ year ]"
-    return
+    /usr/bin/cal && exit
 fi
 
-# can specify month as:
-#   - month number or name
-#   - range of months (separated by a dash)
-if `echo $month | grep -q '-' >/dev/null`; then
-    # range of months
-    startmon=`echo $month | sed 's/-.*//'`
-    endmon=`echo $month | sed 's/.*-//'`
-    # error if either is missing
-    if [ -z "$startmon" -o -z "$endmon" ]; then
-        echo "Invalid date range: $month"
-        return 1
-    fi
-    if `echo $startmon | grep -q '[^0-9]' >/dev/null`; then
-        convmon $startmon && startmon=$?
-    fi
-    if `echo $endmon | grep -q '[^0-9]' >/dev/null`; then
-        convmon $endmon && endmon=$?
-    fi
+# or too many args
+if [ $# -gt 2 ]; then
+    echo "Usage: $0 [ month ] [ year ]" >&2 && exit
+fi
 
-    # We always start with the next occurrence of the month
-    curmon=`/bin/date "+%m"`
-    if (( $curmon > $startmon )); then
-        ((year++))
+# did they specify a year?
+if [ $# -eq 2 ]; then
+    year=$2
+fi
+
+# first arg is one of:
+#    a month range (presence of -)
+#    a month (string or number <= 12)
+#    a year (any other number)
+arg=$1
+
+# No dash? It's either a month or a year
+if ! `echo $arg | grep -q '-' >/dev/null`; then
+    arg=$(conv_to_num $arg)
+    if [ ! $? -eq 0 ]; then
+       exit $?
     fi
-    # the year applies to the starting month. Catch the case where
-    # we need to wrap the year
-    if [ "$startmon" -gt "$endmon" ]; then
-        for ((n=$startmon; n<=12; n++)); do
-            /usr/bin/cal $n $year
-        done
-        # start over again in Jan of the next year
-        startmon=1
-        ((year++))
-    fi
-    for ((n=$startmon; n<=$endmon; n++)); do
-        /usr/bin/cal $n $year
-    done
-else
-    # single month given; the case of just a single arg being a year
-    # was handled above, so we know that the month is a month and the
-    # year is a year
-    if `echo $month | grep -q '[^0-9]' >/dev/null`; then
-        convmon $month && month=$?
-    fi
-    # We always start with the next occurrence of the month
-    # if no specific year was specified; UNLESS the year was
-    # specified on the command line, in which case just do
-    # what was asked
-    if [ $# -eq 1 ]; then
+    if (( $arg > 12 )); then
+        # easy case, just a year
+        /usr/bin/cal $arg
+        exit
+    else
+        # ah, so we have a month
+        # default to current year
+        year=${year-`/bin/date "+%Y"`}
+        # and we always start with the next occurrence of the starting month
         curmon=`/bin/date "+%m"`
-        if (( $curmon > $month )); then
+        if (( $curmon > $arg )); then
             ((year++))
         fi
+        /usr/bin/cal -m $arg ${year}
+        exit
     fi
-    /usr/bin/cal $month $year
 fi
+
+# OK, we have a range
+startmon=`echo $arg | sed 's/-.*//'`
+endmon=`echo $arg | sed 's/.*-//'`
+# error if either is missing
+if [ -z "$startmon" -o -z "$endmon" ]; then
+    echo "Invalid date range: $arg"
+    exit 1
+fi
+
+# make sure they get converted to numbers
+startmon=$(conv_to_num $startmon)
+if $?; then
+   exit $?
+fi
+endmon=$(conv_to_num $endmon)
+if [ ! $? -eq 0 ]; then
+   exit $?
+fi
+# and that they are <= 12
+if [ "$startmon" -gt 12 ]; then
+   echo "Invalid month: $startmon"
+fi
+if [ ! $? -eq 0 ]; then
+   exit $?
+fi
+
+# default to current year
+year=${year-`/bin/date "+%Y"`}
+# and we always start with the next occurrence of the starting month
+curmon=`/bin/date "+%m"`
+if (( $curmon > $startmon )); then
+    ((year++))
+fi
+
+# figure out how many months we need to print out
+monrange=$(( $endmon - $startmon ))
+# do we need to wrap the year?
+if (( $monrange <= 0 )); then
+   monrange=$(( $monrange + 12 ))
+fi
+
+# do it
+/usr/bin/cal -m $startmon -A $monrange $year
+
